# The Qt SDK path
set(QT_SDK_DIR "D:/Qt/Qt5.14.2/5.14.2/msvc2017_64")

# CEF version
SET(CEF_VERSION_MAJOR 86)
SET(CEF_VERSION_MINOR 0)
SET(CEF_VERSION_PATCH 18)

SET(QCEF_WING_EXE "QCefWing")
SET(QCEF_WIDGET_DLL "QCefWidget")
SET(BUILD_PATH "${CMAKE_SOURCE_DIR}/build")
